### ISSUE TITLE
Request, dunst customisation

### ISSUE THREAD

**Issue by bonnebulle** [ztpnk/gotify-dunst#10]
Hello
Thanks, this add a good notification feedback
But i realy cant figure how to customize dunst .
I already read Dunst Documentation .
I just would like persistant / long time notifications .
Do you have a clue ?
Thanks again

**Comment by ztpnk** [comment]
Hey,
dunst works with different urgencies. So you can customize your urgency_low, urgency_normal and urgency_critical settings in the dunst conf for persistant or long time notifications.
Alternatively you can customize the main.py. I have given notify-send the various '-u' options, but you can also use the --expire-time option.
