### ISSUE TITLE
Allow SSL verification

### ISSUE THREAD

**Issue by fdw** [ztpnk/gotify-dunst#12]
I host my own gotify with a self-signed certificate. It's good enough for my purposes, but certainly not ideal.

Would it be possible to allow gotify-dunst to skip the SSL check? Thank you 🙂

**Comment by ztpnk** [comment]
I wouldn't recommend to skip the SSL check.
There is an option to verify a self-signed certificate with the public key for [python requests](https://stackoverflow.com/a/30405947) but I don't know if there is a simple solution for the websockets library too and if I want to include that into the code.

Maybe you can trust your own certificate system-wide or just for [inside the python-environment](https://stackoverflow.com/a/50339149).

**Comment by fdw** [comment]
> I wouldn't recommend to skip the SSL check.

I wouldn't recommend it either ;) but I would expect it's quite a common solution for self-hosted services like gotify. Doing it the right way adds a lot of work for not a lot of gain.

Thanks, anyway :)
