### ISSUE TITLE
CLI support

### ISSUE THREAD

**Issue by pieterhouwen** [ztpnk/gotify-dunst#5]
Hi all,

Is there any way to have the notification come in on the CLI? 

I'm trying to setup a scenario where one of my server makes a backup, publishes it, sends a notification to the backup server with the download URL so my backupserver can download it automatically and store it securely.

Cheers!

**Comment by ztpnk** [comment]
Hi,

I don't know if there is a way to do that. I guess to get notifications in the CLI you have to start a service in the specific shell or make a plugin for it.

To be honest I would recommend you to use rsync or simply ssh for your scenario.
